name: CI

on:
  push:
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Lint with ruff
      run: |
        pipenv run ruff check .

    - name: Type check with mypy
      run: |
        pipenv run mypy app.py src
